# Generated by Django 5.2.5 on 2025-09-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('hostname', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
                ('message_id', models.CharField(blank=True, max_length=20)),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('to_email', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('delay', models.FloatField(blank=True, null=True)),
                ('delays', models.CharField(blank=True, max_length=100)),
                ('dsn', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='logs_maillo_timesta_dcd771_idx')],
            },
        ),
    ]
