# Generated by Django 5.2.5 on 2025-09-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maillog',
            options={'ordering': ['-timestamp']},
        ),
    ]
