# Generated by Django 5.2.5 on 2025-09-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_maillog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillog',
            name='nrcpt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maillog',
            name='relay',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
