# Generated by Django 5.2.5 on 2025-09-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_maillog_nrcpt_maillog_relay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillog',
            name='message_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
