# Generated by Django 5.2.5 on 2025-09-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_maillog_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillog',
            name='message_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['message_id'], name='logs_maillo_message_090885_idx'),
        ),
    ]
